consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  ResendVerificationPayload:
    description: Payload for resending email verification. Contains user email
    example:
      email: Et molestias maxime rem nemo.
    properties:
      email:
        description: User email for verification
        example: Et molestias maxime rem nemo.
        type: string
    required:
    - email
    title: ResendVerificationPayload
    type: object
  UserPayload:
    description: UserPayload
    example:
      active: true
      email: breana@rennerkoepp.com
      externalId: At consequatur saepe.
      fullname: ApPq
      namespaces:
      - Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
      - Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
      - Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
      password: 0arnperc
      roles:
      - Quo quo amet occaecati ut.
      - Quo quo amet occaecati ut.
      sendActivationMail: false
      token: Doloremque aut sed ut impedit voluptatum debitis.
    properties:
      active:
        default: false
        description: Status of user account
        example: true
        type: boolean
      email:
        description: Email of user
        example: breana@rennerkoepp.com
        format: email
        type: string
      externalId:
        description: External id of user
        example: At consequatur saepe.
        type: string
      fullname:
        description: Full name of user
        example: ApPq
        pattern: ^([a-zA-Z0-9 ]{4,30})$
        type: string
      namespaces:
        description: List of namespaces this user belongs to
        example:
        - Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
        - Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
        - Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
        items:
          example: Repudiandae eaque quia cupiditate cumque quibusdam accusantium.
          type: string
        type: array
      password:
        description: Password of user
        example: 0arnperc
        maxLength: 30
        minLength: 6
        type: string
      roles:
        description: Roles of user
        example:
        - Quo quo amet occaecati ut.
        - Quo quo amet occaecati ut.
        items:
          example: Quo quo amet occaecati ut.
          type: string
        type: array
      sendActivationMail:
        default: true
        description: Status of user account
        example: false
        type: boolean
      token:
        description: Email verification token
        example: Doloremque aut sed ut impedit voluptatum debitis.
        type: string
    required:
    - fullname
    - email
    title: UserPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1458609066
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1458609066
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  users:
    description: users media type (default view)
    example:
      active: true
      email: thad@herman.name
      externalId: Ullam occaecati quae odio rerum aliquid in.
      fullname: dkPRrKW
      id: Reprehenderit ea quam optio placeat.
      roles:
      - Quo quo amet occaecati ut.
      - Quo quo amet occaecati ut.
      - Quo quo amet occaecati ut.
    properties:
      active:
        default: false
        description: Status of user account
        example: true
        type: boolean
      email:
        description: Email of user
        example: thad@herman.name
        format: email
        type: string
      externalId:
        description: External id of user
        example: Ullam occaecati quae odio rerum aliquid in.
        type: string
      fullname:
        description: Full name of user
        example: dkPRrKW
        pattern: ^([a-zA-Z0-9 ]{4,30})$
        type: string
      id:
        description: Unique user ID
        example: Reprehenderit ea quam optio placeat.
        type: string
      roles:
        description: Roles of user
        example:
        - Quo quo amet occaecati ut.
        - Quo quo amet occaecati ut.
        - Quo quo amet occaecati ut.
        items:
          example: Quo quo amet occaecati ut.
          type: string
        type: array
    required:
    - id
    - fullname
    - email
    - roles
    - externalId
    - active
    title: 'Mediatype identifier: application/vnd.goa.user+json; view=default'
    type: object
host: localhost:8080
info:
  description: A service that provides user registration
  title: The user registration microservice
  version: "1.0"
paths:
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download swagger-ui/dist
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
  /users/register:
    post:
      description: Creates user
      operationId: user#register
      parameters:
      - description: UserPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: register user
      tags:
      - user
  /users/register/resend-verification:
    post:
      description: Resends verification email and resets valiation tokens
      operationId: user#resendVerification
      parameters:
      - description: Payload for resending email verification. Contains user email
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ResendVerificationPayload'
      produces:
      - application/vnd.goa.error
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: resendVerification user
      tags:
      - user
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
